
server:
  port: 8090
  
custom:
  property: "#{T(reactive.proxy.properties.PropertyGetter).getProperty('custom_property')?:'defaultValue'}"
  
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: dummy-route
#        uri: http://localhost:8080
#        predicates:
#        - Path=/dummy/**